name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Singapore
          base: header
          
          # Enable more plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_activity: yes
          plugin_contributors: yes
          plugin_followup: yes
          plugin_repositories: yes
          plugin_topics: yes
          plugin_achievements: yes
          plugin_forked: yes
          plugin_code: yes
          
          plugin_languages_ignored: VHDL, SystemVerilog, JavaScript, HTML, Verilog
          contributors_sections: commits, issues, pull-requests

          plugin_repositories_featured: sustech-cs304/galaguide, Charley-xiao/ecs171-project, Charley-xiao/balance-it, Charley-xiao/nogenshin

          # Additional configuration for order and layout
          config_order: base.header, isocalendar, repositories, languages, code, stars, contributors, activity, followup, topics, achievements, forked
          config_display: large
